# Generated by Django 5.2.9 on 2025-12-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_alter_category_options_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[("Drafts", "Drafts"), ("Published", "Published")],
                default="Draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
