# Generated by Django 5.2.9 on 2025-12-30 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assignment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="about",
            old_name="about_desciption",
            new_name="about_description",
        ),
    ]
