# Generated by Django 5.2.9 on 2025-12-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignment", "0002_rename_about_desciption_about_about_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="about_description",
            field=models.CharField(max_length=350, verbose_name="Description"),
        ),
    ]
