# Generated by Django 5.2.9 on 2025-12-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignment", "0003_alter_about_about_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="about_description",
            field=models.TextField(max_length=500, verbose_name="Description"),
        ),
    ]
