# Generated by Django 5.2.9 on 2025-12-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignment", "0004_alter_about_about_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=25, verbose_name="Platform")),
                ("social_link", models.URLField(verbose_name="Social Link")),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "SocialLink",
                "verbose_name_plural": "Social Links",
            },
        ),
    ]
